### ISSUE TITLE
Homebridge search result

### ISSUE THREAD

**Issue by h0mesmart** [t-j-n/homebridge-mystromoutlet#1]
Hello there,

I'd like to use this plugin but as I did a search on homebridge UI there is no result. Can you help me please. Thank you
FYI I use homebridge 1.1.3

**Comment by t-j-n** [comment]
Hi h0mesmart

You’ll have to install the plugin manually by cloning the github repo or downloading it as a zip file. Beware that this is really a hack and might not work properly and I that I am not maintaining it anymore as I have switched to connecting my plugs directly to HomeKit.
Feel free to clone and improve the code, though.

**Comment by h0mesmart** [comment]
Hello, 

Gotcha. Thx
